### ISSUE TITLE
Can I ask you some questions about sdl2?

### ISSUE THREAD

**Issue by thetbw** [ShoesForClues/MiyooMiniSDL2#1]
I want porting a tool to miyoo mini, he uses sdl2, but I don't know what to do, I'm not a c developer. I successfully ran the sdl1 program on the miyoo mini, because it comes with the sdl1 library, but what should I do with sdl2.
I compiled sdl2 using gcc of miyoo mini and then compiled my program, but it doesn't start

**Comment by thetbw** [comment]
sdl_error is : No available video device

**Comment by ShoesForClues** [comment]
The device has no hardware acceleration so you have to use software rendering instead. SDL1.2 originally had support for software rendering (fbcon) but they removed it in SDL2 for some reason. So instead you can use DirectFB, which is what I used.
